language: java
sudo: required
cache: 
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8

services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE carpnd;" -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'postgres';" -U postgres

script: 
  - cd desapp-groupf-backend 
  - mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8 -DJDBC_DATABASE_URL=jdbc:postgresql://localhost/d4sd0fn020bobf

  
deploy:
  - provider: heroku
    skip_cleanup: true
    api_key: a82fab68-408c-4b23-a9bf-3d14a7f0a5e4
    app: desapp-unq-grupof
