language: java
sudo: required
cache: 
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8

ignore:
  - desapp-groupf-backend/src/test/java/services/*
script: 
  - cd desapp-groupf-backend 
  - mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
  
deploy:
  - provider: heroku
    skip_cleanup: true
    api_key: a82fab68-408c-4b23-a9bf-3d14a7f0a5e4
    app: desapp-unq-grupof
